### ISSUE TITLE
can we Revert to minsdk 21 ? 

### ISSUE THREAD

**Issue by rohitsangwan01** [Dev-hwang/flutter_foreground_task#37]
Hey , i just noticed one thing that my app size increases almost double after changing minsdk from 21 -> 23 , but i can't use 21 with this pcakcge , so any workaround or possible to set minsdk 21 for your package

**Comment by Dev-hwang** [comment]
I set the minimum sdk to 23 because of the stability of the permission request and foreground service. I can downgrade to 21, but I don't know what compatibility issues it will cause.

Fork this project to set the sdk to 21.

**Comment by Dev-hwang** [comment]
@rohitsangwan01

If you use the branch below, you can also use this plugin in version 21, but stability cannot be guaranteed.

Add the following line to your `pubspec.yaml` file.

```yaml
dependency_overrides:
  flutter_foreground_task:
    git:
      url: https://github.com/Dev-hwang/flutter_foreground_task.git
      ref: minsdk_21
```
