### ISSUE TITLE
a callback when the user presses on the notification itself

### ISSUE THREAD

**Issue by madatr** [Dev-hwang/flutter_foreground_task#41]
Hi,

Is there a way to catch the event whenever the user presses on the notification and summons the app? similar to onButtonPressed

Thanks

**Comment by Dev-hwang** [comment]
There is not. I will consider implementing that feature.

**Comment by insidewhy** [comment]
I also really need this, the foreground task starts a report for my app and when I click on the notification I'd like to route directly to the report rather than unminimising the app at whatever route it happens to be displaying.

**Comment by insidewhy** [comment]
@irjayjay I'm trying to add this feature right now

**Comment by insidewhy** [comment]
@irjayjay Well I got it working absolutely fine, then all of a sudden after pulling my package I keep getting

```
/android/src/main/kotlin/com/pravera/flutter_foreground_task/MethodCallHandlerImpl.kt: (9, 50): Unresolved reference: ErrorHandleUtils
```

Even though `ErrorHandleUtils` blatantly exists. Have no idea why a file in the project can't be seen by the project itself.

You can try adding this to your `pubspec.yaml`:

```
  flutter_foreground_task:
    git:
      url: git@github.com:sol-x/flutter_foreground_task
      ref: feature/41
```

But I have to comment out all references to `ErrorHandleUtils` to get it to compile.

At this point I just don't know what to do. The error message makes no sense. For me flutter development has been a pain from the beginning, death by a thousand cuts with so many little annoyances. This one has defeated me.

**Comment by insidewhy** [comment]
@irjayjay Finally got it working, the error I was facing was just caused by flutter platform bugs. I had to clear out my `pub-cache` and `flutter clean` then it went away by itself. Argh.

PR is here https://github.com/Dev-hwang/flutter_foreground_task/pull/74

Using this branch in my app now and it's working great.

```yaml
  flutter_foreground_task:
    git:
      url: git@github.com:sol-x/flutter_foreground_task
      ref: feature/41
```

In your `onNotificationPressed` handler you'll need to use `launchApp("/some-route")` where the handler for the `"/some-route"` route will restore the state when the app has exited (and therefore there is no `sendPort`). When the `sendPort` exists you can simply use that to send a message to restore whatever data you need.

**Comment by irjayjay** [comment]
Ah, pub cache and gradle cache, biggest time wasters!

**Comment by irjayjay** [comment]
Well done for sticking to it @insidewhy! This is such a core feature!

**Comment by Dev-hwang** [comment]
@madatr @irjayjay @insidewhy

The function was implemented with the help of @insidewhy. I will upgrade the plugin after updating the examples and improving the functions of the plugin.

Can try the features first before release.
```yaml
dependencies:
  flutter_foreground_task:
    git:
      url: https://github.com/Dev-hwang/flutter_foreground_task.git
      ref: master
```

Here [example](https://github.com/Dev-hwang/flutter_foreground_task/blob/master/example/lib/main.dart). Please let me know if there is anything I need to add.

Thanks for @insidewhy help in implementing the feature.
